
filter:
    paths: ['src/*']
    excluded_paths: [tests/*, vendor/*, src/library/tgm/*, src/library/timber/*]

checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: false
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
        no_unnecessary_function_call_in_for_loop: true
        avoid_unnecessary_concatenation: true
        duplication: true
        prefer_sapi_constant: true
        variable_existence: true
        useless_calls: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parameter_non_unique: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        deprecated_code_usage: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        avoid_useless_overridden_methods: true
        avoid_conflicting_incrementers: true
        assignment_of_null_return: true
        verify_access_scope_valid: true
        too_many_arguments: true
        symfony_request_injection: true
        parameter_doc_comments: true
        argument_type_checks: true
        avoid_corrupting_byteorder_marks: true
        avoid_entity_manager_injection: true
        catch_class_exists: true
        encourage_shallow_comparison: false
        foreach_traversable: true
        foreach_usable_as_reference: true
        instanceof_class_exists: true
        method_calls_on_non_object: true
        missing_arguments: true
        no_duplicate_arguments: false
        require_php_tag_first: true
        return_doc_comments: true
        verify_property_names: true
        verify_argument_usable_as_reference: true
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        simplify_boolean_return: true
        properties_in_camelcaps: true
        prefer_while_loop_over_for_loop: true
        phpunit_assertions: true
        parameters_in_camelcaps: true
        param_doc_comment_if_not_inferrable: true
        optional_parameters_at_the_end: true
        no_short_variable_names:
            minimum: '3'
        no_short_method_names:
            minimum: ''
        no_goto: true
        newline_at_end_of_file: true
        more_specific_types_in_doc_comments: true
        line_length:
            max_length: '160'
        function_in_camel_caps: true
        fix_line_ending: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        classes_in_camel_caps: true
        avoid_unnecessary_concatenation: true
        avoid_todo_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_fixme_comments: true

tools:
    php_changetracking:          true

    php_cs_fixer:
        enabled:                 true
        extensions:
            - php
        command:                 php-cs-fixer
        config:
            level:               all
        filter:
            excluded_paths:
                - 'bin/*'
                - 'vendor/*'
                - 'tests/*'
                - 'src/library/tgm/*'
                - 'src/library/timber/*'

    php_loc:
        enabled:                 true
        extensions:
            - php
        command:                 phploc
        filter:
            excluded_paths:
                - bin
                - vendor
                - tests/*
                - src/library/tgm/*
                - src/library/timber/*

    php_mess_detector:
        enabled:                 true
        extensions:
            - php
        command:                 phpmd
        filter:
            excluded_paths:
                - 'bin/*'
                - 'vendor/*'
                - 'tests/*'
                - 'src/library/tgm/*'
                - 'src/library/timber/*'
    php_cpd:
        enabled:                 false

    php_analyzer:
        enabled:                 true
        extensions:
            - php
        filter:
            excluded_paths:
                - 'bin/*'
                - 'vendor/*'
                - 'tests/*'
                - 'src/library/tgm/*'
                - 'src/library/timber/*'

    php_pdepend:
        enabled:                 true
        suffixes:
            - php
        command:                 pdepend
        excluded_dirs:
            - bin
            - vendor
            - tests/*
            - src/library/tgm/*
            - src/library/timber/*

    sensiolabs_security_checker: true
